using System;
using System.Collections.Generic;
using System.Text;
using Microsoft.EntityFrameworkCore;

namespace Molemax.Models
{
    public class DEFBodymapPositionSeed
    {
        public static void GenerateSeed(ModelBuilder modelBuilder)
        {
            #region DEFBodymapPositionSeed
            modelBuilder.Entity<DEFBodymapPosition>().HasData(new DEFBodymapPosition { id = 1, body_pos_id = 1, position_text = "Standing Front", location_text = "Front face and neck", dummy_position = 7, X1 = 10177648, Y1 = 6774396, X2 = 1048297704, Y2 = 1063580229, body_type = 1, bar_location_text = "on BLUE coloured position", light_intensity_text = "Illumination light is on", other_instruction_text = "Choose A, B or C sub-position, depend on patient height.", remark_text = "For this position follow-up, use the same camera bar position and sub position (A, B or C).", hint_text = "14390128" });
            modelBuilder.Entity<DEFBodymapPosition>().HasData(new DEFBodymapPosition { id = 2, body_pos_id = 2, position_text = "Standing Right", location_text = "Right face and neck", dummy_position = 7, X1 = 10177648, Y1 = 1090677814, X2 = 1048297704, Y2 = 2147483647, body_type = 1, bar_location_text = "on BLUE coloured position", light_intensity_text = "Illumination light is on", other_instruction_text = "Choose A, B or C sub-position, depend on patient height.", remark_text = "For this position follow-up, use the same camera bar position and sub position (A, B or C).", hint_text = "14390128" });
            modelBuilder.Entity<DEFBodymapPosition>().HasData(new DEFBodymapPosition { id = 3, body_pos_id = 3, position_text = "Standing Left", location_text = "Left face and neck", dummy_position = 7, X1 = 1089008295, Y1 = 6774396, X2 = 2137305999, Y2 = 1063580229, body_type = 1, bar_location_text = "on BLUE coloured position", light_intensity_text = "Illumination light is on", other_instruction_text = "Choose A, B or C sub-position, depend on patient height.", remark_text = "For this position follow-up, use the same camera bar position and sub position (A, B or C).", hint_text = "14390128" });
            modelBuilder.Entity<DEFBodymapPosition>().HasData(new DEFBodymapPosition { id = 4, body_pos_id = 4, position_text = "Sitting in chair", location_text = "Sole of right foot", dummy_position = 9, X1 = 10177648, Y1 = 1090677814, X2 = 1048297704, Y2 = 2147483647, body_type = 1, bar_location_text = "on WHITE coloured position", light_intensity_text = "Illumination light is on", other_instruction_text = "Choose A, B or C sub-position, depend on patient height.", remark_text = "For this position follow-up, use the same camera bar position and sub position (A, B or C).", hint_text = "16777215" });
            modelBuilder.Entity<DEFBodymapPosition>().HasData(new DEFBodymapPosition { id = 5, body_pos_id = 5, position_text = "Sitting in chair", location_text = "Sole of left foot", dummy_position = 9, X1 = 1089008295, Y1 = 1090677814, X2 = 2137305999, Y2 = 2147483647, body_type = 1, bar_location_text = "on WHITE coloured position", light_intensity_text = "Illumination light is on", other_instruction_text = "Choose A, B or C sub-position, depend on patient height.", remark_text = "For this position follow-up, use the same camera bar position and sub position (A, B or C).", hint_text = "16777215" });
            modelBuilder.Entity<DEFBodymapPosition>().HasData(new DEFBodymapPosition { id = 6, body_pos_id = 6, position_text = "Standing Right", location_text = "Right forearm and open hand", dummy_position = 5, X1 = 1160251828, Y1 = 108390342, X2 = 1424870666, Y2 = 541951709, body_type = 1, bar_location_text = "on BLUE coloured position", light_intensity_text = "Illumination light is on", other_instruction_text = "Choose A, B or C sub-position, depend on patient height.", remark_text = "For this position follow-up, use the same camera bar position and sub position (A, B or C).", hint_text = "14390128" });
            modelBuilder.Entity<DEFBodymapPosition>().HasData(new DEFBodymapPosition { id = 7, body_pos_id = 7, position_text = "Standing Right", location_text = "Right upper arm, anterior", dummy_position = 5, X1 = 814211809, Y1 = 487756538, X2 = 1251850657, Y2 = 677439636, body_type = 1, bar_location_text = "on BLUE coloured position", light_intensity_text = "Illumination light is on", other_instruction_text = "Choose A, B or C sub-position, depend on patient height.", remark_text = "For this position follow-up, use the same camera bar position and sub position (A, B or C).", hint_text = "14390128" });
            modelBuilder.Entity<DEFBodymapPosition>().HasData(new DEFBodymapPosition { id = 8, body_pos_id = 8, position_text = "Standing Right", location_text = "Right flank with arm raised", dummy_position = 5, X1 = 742968276, Y1 = 630018862, X2 = 1180607123, Y2 = 989061869, body_type = 1, bar_location_text = "on LIGHT BLUE coloured position", light_intensity_text = "Illumination light is on", other_instruction_text = "Choose A, B or C sub-position, depend on patient height.", remark_text = "For this position follow-up, use the same camera bar position and sub position (A, B or C).", hint_text = "15329708" });
            modelBuilder.Entity<DEFBodymapPosition>().HasData(new DEFBodymapPosition { id = 9, body_pos_id = 9, position_text = "Standing Right", location_text = "Right thigh and hip", dummy_position = 5, X1 = 742968276, Y1 = 989061869, X2 = 1160251828, Y2 = 1544562371, body_type = 1, bar_location_text = "on YELLOW coloured position", light_intensity_text = "Illumination light is on", other_instruction_text = "Choose A, B or C sub-position, depend on patient height.", remark_text = "For this position follow-up, use the same camera bar position and sub position (A, B or C).", hint_text = "65535" });
            modelBuilder.Entity<DEFBodymapPosition>().HasData(new DEFBodymapPosition { id = 10, body_pos_id = 10, position_text = "Standing Right", location_text = "Right lateral calf and foot", dummy_position = 5, X1 = 702257686, Y1 = 1544562371, X2 = 1200962419, Y2 = 2039093305, body_type = 1, bar_location_text = "on WHITE coloured position", light_intensity_text = "Illumination light is on", other_instruction_text = "Choose A, B or C sub-position, depend on patient height.", remark_text = "For this position follow-up, use the same camera bar position and sub position (A, B or C).", hint_text = "16777215" });
            modelBuilder.Entity<DEFBodymapPosition>().HasData(new DEFBodymapPosition { id = 11, body_pos_id = 11, position_text = "Standing Right", location_text = "Left inner arm and hand", dummy_position = 6, X1 = 1099185943, Y1 = 101615945, X2 = 1638601266, Y2 = 657116447, body_type = 1, bar_location_text = "on BLUE coloured position", light_intensity_text = "Illumination light is on", other_instruction_text = "Choose A, B or C sub-position, depend on patient height.", remark_text = "For this position follow-up, use the same camera bar position and sub position (A, B or C).", hint_text = "14390128" });
            modelBuilder.Entity<DEFBodymapPosition>().HasData(new DEFBodymapPosition { id = 12, body_pos_id = 12, position_text = "Standing Left", location_text = "Left forearm and open hand", dummy_position = 3, X1 = 712435333, Y1 = 108390342, X2 = 977054171, Y2 = 541951709, body_type = 1, bar_location_text = "on BLUE coloured position", light_intensity_text = "Illumination light is on", other_instruction_text = "Choose A, B or C sub-position, depend on patient height.", remark_text = "For this position follow-up, use the same camera bar position and sub position (A, B or C).", hint_text = "14390128" });
            modelBuilder.Entity<DEFBodymapPosition>().HasData(new DEFBodymapPosition { id = 13, body_pos_id = 13, position_text = "Standing Left", location_text = "Left upper arm, anterior", dummy_position = 3, X1 = 885455343, Y1 = 487756538, X2 = 1333271838, Y2 = 677439636, body_type = 1, bar_location_text = "on BLUE coloured position", light_intensity_text = "Illumination light is on", other_instruction_text = "Choose A, B or C sub-position, depend on patient height.", remark_text = "For this position follow-up, use the same camera bar position and sub position (A, B or C).", hint_text = "14390128" });
            modelBuilder.Entity<DEFBodymapPosition>().HasData(new DEFBodymapPosition { id = 14, body_pos_id = 14, position_text = "Standing Left", location_text = "Left flank with arm raised", dummy_position = 3, X1 = 956698876, Y1 = 630018862, X2 = 1394337723, Y2 = 989061869, body_type = 1, bar_location_text = "on LIGHT BLUE coloured position", light_intensity_text = "Illumination light is on", other_instruction_text = "Choose A, B or C sub-position, depend on patient height.", remark_text = "For this position follow-up, use the same camera bar position and sub position (A, B or C).", hint_text = "15329708" });
            modelBuilder.Entity<DEFBodymapPosition>().HasData(new DEFBodymapPosition { id = 15, body_pos_id = 15, position_text = "Standing Left", location_text = "Left thigh and hip", dummy_position = 3, X1 = 977054171, Y1 = 989061869, X2 = 1394337723, Y2 = 1544562371, body_type = 1, bar_location_text = "on YELLOW coloured position", light_intensity_text = "Illumination light is on", other_instruction_text = "Choose A, B or C sub-position, depend on patient height.", remark_text = "For this position follow-up, use the same camera bar position and sub position (A, B or C).", hint_text = "65535" });
            modelBuilder.Entity<DEFBodymapPosition>().HasData(new DEFBodymapPosition { id = 16, body_pos_id = 16, position_text = "Standing Left", location_text = "Left lateral calf and foot", dummy_position = 3, X1 = 936343581, Y1 = 1544562371, X2 = 1435048314, Y2 = 2039093305, body_type = 1, bar_location_text = "on WHITE coloured position", light_intensity_text = "Illumination light is on", other_instruction_text = "Choose A, B or C sub-position, depend on patient height.", remark_text = "For this position follow-up, use the same camera bar position and sub position (A, B or C).", hint_text = "16777215" });
            modelBuilder.Entity<DEFBodymapPosition>().HasData(new DEFBodymapPosition { id = 17, body_pos_id = 17, position_text = "Standing Left", location_text = "Right inner arm and hand", dummy_position = 2, X1 = 498704733, Y1 = 101615945, X2 = 1038120057, Y2 = 657116447, body_type = 1, bar_location_text = "on BLUE coloured position", light_intensity_text = "Illumination light is on", other_instruction_text = "Choose A, B or C sub-position, depend on patient height.", remark_text = "For this position follow-up, use the same camera bar position and sub position (A, B or C).", hint_text = "14390128" });
            modelBuilder.Entity<DEFBodymapPosition>().HasData(new DEFBodymapPosition { id = 18, body_pos_id = 18, position_text = "Standing Front", location_text = "Left chest", dummy_position = 1, X1 = 1068653000, Y1 = 406463782, X2 = 1384160076, Y2 = 711311618, body_type = 1, bar_location_text = "on LIGHT BLUE coloured position", light_intensity_text = "Illumination light is on", other_instruction_text = "Choose A, B or C sub-position, depend on patient height.", remark_text = "For this position follow-up, use the same camera bar position and sub position (A, B or C).", hint_text = "15329708" });
            modelBuilder.Entity<DEFBodymapPosition>().HasData(new DEFBodymapPosition { id = 19, body_pos_id = 19, position_text = "Standing Front", location_text = "Right chest", dummy_position = 1, X1 = 742968276, Y1 = 406463782, X2 = 1058475352, Y2 = 711311618, body_type = 1, bar_location_text = "on LIGHT BLUE coloured position", light_intensity_text = "Illumination light is on", other_instruction_text = "Choose A, B or C sub-position, depend on patient height.", remark_text = "For this position follow-up, use the same camera bar position and sub position (A, B or C).", hint_text = "15329708" });
            modelBuilder.Entity<DEFBodymapPosition>().HasData(new DEFBodymapPosition { id = 20, body_pos_id = 20, position_text = "Standing Front", location_text = "Left abdomen", dummy_position = 1, X1 = 1068653000, Y1 = 670665240, X2 = 1323094190, Y2 = 1043257040, body_type = 1, bar_location_text = "on LIGHT BLUE coloured position", light_intensity_text = "Illumination light is on", other_instruction_text = "Choose A, B or C sub-position, depend on patient height.", remark_text = "For this position follow-up, use the same camera bar position and sub position (A, B or C).", hint_text = "15329708" });
            modelBuilder.Entity<DEFBodymapPosition>().HasData(new DEFBodymapPosition { id = 21, body_pos_id = 21, position_text = "Standing Front", location_text = "Right abdomen", dummy_position = 1, X1 = 804034162, Y1 = 670665240, X2 = 1058475352, Y2 = 1043257040, body_type = 1, bar_location_text = "on LIGHT BLUE coloured position", light_intensity_text = "Illumination light is on", other_instruction_text = "Choose A, B or C sub-position, depend on patient height.", remark_text = "For this position follow-up, use the same camera bar position and sub position (A, B or C).", hint_text = "15329708" });
            modelBuilder.Entity<DEFBodymapPosition>().HasData(new DEFBodymapPosition { id = 22, body_pos_id = 22, position_text = "Standing Front", location_text = "Upper legs, anterior", dummy_position = 1, X1 = 773501219, Y1 = 1009385058, X2 = 1363804781, Y2 = 1537787974, body_type = 1, bar_location_text = "on YELLOW coloured position", light_intensity_text = "Illumination light is on", other_instruction_text = "Choose A, B or C sub-position, depend on patient height.", remark_text = "For this position follow-up, use the same camera bar position and sub position (A, B or C).", hint_text = "65535" });
            modelBuilder.Entity<DEFBodymapPosition>().HasData(new DEFBodymapPosition { id = 23, body_pos_id = 23, position_text = "Standing Front", location_text = "Lower legs, anterior", dummy_position = 1, X1 = 773501219, Y1 = 1537787974, X2 = 1363804781, Y2 = 2045867702, body_type = 1, bar_location_text = "on WHITE coloured position", light_intensity_text = "Illumination light is on", other_instruction_text = "Choose A, B or C sub-position, depend on patient height.", remark_text = "For this position follow-up, use the same camera bar position and sub position (A, B or C).", hint_text = "16777215" });
            modelBuilder.Entity<DEFBodymapPosition>().HasData(new DEFBodymapPosition { id = 24, body_pos_id = 24, position_text = "Standing Front", location_text = "Right inner leg", dummy_position = 2, X1 = 773501219, Y1 = 1158421778, X2 = 1262028304, Y2 = 2045867702, body_type = 1, bar_location_text = "on WHITE coloured position", light_intensity_text = "Illumination light is on", other_instruction_text = "Choose A, B or C sub-position, depend on patient height.", remark_text = "For this position follow-up, use the same camera bar position and sub position (A, B or C).", hint_text = "16777215" });
            modelBuilder.Entity<DEFBodymapPosition>().HasData(new DEFBodymapPosition { id = 25, body_pos_id = 25, position_text = "Standing Front", location_text = "Left inner leg", dummy_position = 6, X1 = 875277695, Y1 = 1158421778, X2 = 1363804781, Y2 = 2045867702, body_type = 1, bar_location_text = "on WHITE coloured position", light_intensity_text = "Illumination light is on", other_instruction_text = "Choose A, B or C sub-position, depend on patient height.", remark_text = "For this position follow-up, use the same camera bar position and sub position (A, B or C).", hint_text = "16777215" });
            modelBuilder.Entity<DEFBodymapPosition>().HasData(new DEFBodymapPosition { id = 26, body_pos_id = 26, position_text = "Standing Front", location_text = "Both palms", dummy_position = 8, X1 = 10177648, Y1 = 1090677814, X2 = 2137305999, Y2 = 2147483647, body_type = 1, bar_location_text = "on LIGHT BLUE coloured position", light_intensity_text = "Illumination light is on", other_instruction_text = "Choose A, B or C sub-position, depend on patient height.", remark_text = "For this position follow-up, use the same camera bar position and sub position (A, B or C).", hint_text = "15329708" });
            modelBuilder.Entity<DEFBodymapPosition>().HasData(new DEFBodymapPosition { id = 27, body_pos_id = 27, position_text = "Standing Rear", location_text = "Back of neck", dummy_position = 4, X1 = 905810638, Y1 = 291299044, X2 = 1231495362, Y2 = 426786971, body_type = 1, bar_location_text = "on BLUE coloured position", light_intensity_text = "Illumination light is on", other_instruction_text = "Choose A, B or C sub-position, depend on patient height.", remark_text = "For this position follow-up, use the same camera bar position and sub position (A, B or C).", hint_text = "14390128" });
            modelBuilder.Entity<DEFBodymapPosition>().HasData(new DEFBodymapPosition { id = 28, body_pos_id = 28, position_text = "Standing Rear", location_text = "Left upper back and arm, posterior", dummy_position = 4, X1 = 590303562, Y1 = 406463782, X2 = 1058475352, Y2 = 711311618, body_type = 1, bar_location_text = "on LIGHT BLUE coloured position", light_intensity_text = "Illumination light is on", other_instruction_text = "Choose A, B or C sub-position, depend on patient height.", remark_text = "For this position follow-up, use the same camera bar position and sub position (A, B or C).", hint_text = "15329708" });
            modelBuilder.Entity<DEFBodymapPosition>().HasData(new DEFBodymapPosition { id = 29, body_pos_id = 29, position_text = "Standing Rear", location_text = "Right upper back and arm, posterior", dummy_position = 4, X1 = 1068653000, Y1 = 406463782, X2 = 1536824790, Y2 = 711311618, body_type = 1, bar_location_text = "on LIGHT BLUE coloured position", light_intensity_text = "Illumination light is on", other_instruction_text = "Choose A, B or C sub-position, depend on patient height.", remark_text = "For this position follow-up, use the same camera bar position and sub position (A, B or C).", hint_text = "15329708" });
            modelBuilder.Entity<DEFBodymapPosition>().HasData(new DEFBodymapPosition { id = 30, body_pos_id = 30, position_text = "Standing Rear", location_text = "Left lower back and arm, posterior", dummy_position = 4, X1 = 559770619, Y1 = 670665240, X2 = 1058475352, Y2 = 894220320, body_type = 1, bar_location_text = "on LIGHT BLUE coloured position", light_intensity_text = "Illumination light is on", other_instruction_text = "Choose A, B or C sub-position, depend on patient height.", remark_text = "For this position follow-up, use the same camera bar position and sub position (A, B or C).", hint_text = "15329708" });
            modelBuilder.Entity<DEFBodymapPosition>().HasData(new DEFBodymapPosition { id = 31, body_pos_id = 31, position_text = "Standing Rear", location_text = "Right lower back and arm, posterior", dummy_position = 4, X1 = 1068653000, Y1 = 670665240, X2 = 1577535380, Y2 = 894220320, body_type = 1, bar_location_text = "on LIGHT BLUE coloured position", light_intensity_text = "Illumination light is on", other_instruction_text = "Choose A, B or C sub-position, depend on patient height.", remark_text = "For this position follow-up, use the same camera bar position and sub position (A, B or C).", hint_text = "15329708" });
            modelBuilder.Entity<DEFBodymapPosition>().HasData(new DEFBodymapPosition { id = 32, body_pos_id = 32, position_text = "Standing Rear", location_text = "Buttocks and upper legs, posterior", dummy_position = 4, X1 = 559770619, Y1 = 900994716, X2 = 1577535380, Y2 = 1483592803, body_type = 1, bar_location_text = "on YELLOW coloured position", light_intensity_text = "Illumination light is on", other_instruction_text = "Choose A, B or C sub-position, depend on patient height.", remark_text = "For this position follow-up, use the same camera bar position and sub position (A, B or C).", hint_text = "65535" });
            modelBuilder.Entity<DEFBodymapPosition>().HasData(new DEFBodymapPosition { id = 33, body_pos_id = 33, position_text = "Standing Rear", location_text = "Lower legs, posterior", dummy_position = 4, X1 = 773501219, Y1 = 1490367200, X2 = 1363804781, Y2 = 2045867702, body_type = 1, bar_location_text = "on WHITE coloured position", light_intensity_text = "Illumination light is on", other_instruction_text = "Choose A, B or C sub-position, depend on patient height.", remark_text = "For this position follow-up, use the same camera bar position and sub position (A, B or C).", hint_text = "16777215" });
            modelBuilder.Entity<DEFBodymapPosition>().HasData(new DEFBodymapPosition { id = 34, body_pos_id = 1, position_text = "Standing Front", location_text = "Face frontal", dummy_position = 7, X1 = 10177648, Y1 = 6774396, X2 = 1048297704, Y2 = 1063580229, body_type = 0, bar_location_text = "on BLUE coloured position", light_intensity_text = "Illumination light is on", other_instruction_text = "Choose A, B or C sub-position, depend on patient height.", remark_text = "For this position follow-up, use the same camera bar position and sub position (A, B or C).", hint_text = "14390128" });
            modelBuilder.Entity<DEFBodymapPosition>().HasData(new DEFBodymapPosition { id = 35, body_pos_id = 2, position_text = "Standing Right", location_text = "Right side of face", dummy_position = 7, X1 = 1089008295, Y1 = 6774396, X2 = 2137305999, Y2 = 1063580229, body_type = 0, bar_location_text = "on BLUE coloured position", light_intensity_text = "Illumination light is on", other_instruction_text = "Choose A, B or C sub-position, depend on patient height.", remark_text = "For this position follow-up, use the same camera bar position and sub position (A, B or C).", hint_text = "14390128" });
            modelBuilder.Entity<DEFBodymapPosition>().HasData(new DEFBodymapPosition { id = 36, body_pos_id = 3, position_text = "Standing Left", location_text = "Left side of face", dummy_position = 7, X1 = 10177648, Y1 = 1090677814, X2 = 1048297704, Y2 = 2147483647, body_type = 0, bar_location_text = "on BLUE coloured position", light_intensity_text = "Illumination light is on", other_instruction_text = "Choose A, B or C sub-position, depend on patient height.", remark_text = "For this position follow-up, use the same camera bar position and sub position (A, B or C).", hint_text = "14390128" });
            modelBuilder.Entity<DEFBodymapPosition>().HasData(new DEFBodymapPosition { id = 37, body_pos_id = 4, position_text = "Standing Front", location_text = "Neck to chest above navel", dummy_position = 1, X1 = 722612981, Y1 = 413238178, X2 = 1424870666, Y2 = 914543509, body_type = 0, bar_location_text = "on LIGHT BLUE coloured position", light_intensity_text = "Illumination light is on", other_instruction_text = "Choose A, B or C sub-position, depend on patient height.", remark_text = "For this position follow-up, use the same camera bar position and sub position (A, B or C).", hint_text = "15329708" });
            modelBuilder.Entity<DEFBodymapPosition>().HasData(new DEFBodymapPosition { id = 38, body_pos_id = 5, position_text = "Standing Front", location_text = "Stomach only", dummy_position = 1, X1 = 763323571, Y1 = 724860411, X2 = 1373982428, Y2 = 1083903418, body_type = 0, bar_location_text = "on LIGHT BLUE coloured position", light_intensity_text = "Illumination light is on", other_instruction_text = "Choose A, B or C sub-position, depend on patient height.", remark_text = "For this position follow-up, use the same camera bar position and sub position (A, B or C).", hint_text = "15329708" });
            modelBuilder.Entity<DEFBodymapPosition>().HasData(new DEFBodymapPosition { id = 39, body_pos_id = 6, position_text = "Standing Rear", location_text = "Back of head to waist", dummy_position = 4, X1 = 722612981, Y1 = 108390342, X2 = 1424870666, Y2 = 880671527, body_type = 0, bar_location_text = "on LIGHT BLUE coloured position", light_intensity_text = "Illumination light is on", other_instruction_text = "Choose A, B or C sub-position, depend on patient height.", remark_text = "For this position follow-up, use the same camera bar position and sub position (A, B or C).", hint_text = "15329708" });
            modelBuilder.Entity<DEFBodymapPosition>().HasData(new DEFBodymapPosition { id = 40, body_pos_id = 7, position_text = "Standing Rear", location_text = "Waist to back of knee", dummy_position = 4, X1 = 763323571, Y1 = 880671527, X2 = 1353627133, Y2 = 1497141596, body_type = 0, bar_location_text = "on YELLOW coloured position", light_intensity_text = "Illumination light is on", other_instruction_text = "Choose A, B or C sub-position, depend on patient height.", remark_text = "For this position follow-up, use the same camera bar position and sub position (A, B or C).", hint_text = "65535" });
            modelBuilder.Entity<DEFBodymapPosition>().HasData(new DEFBodymapPosition { id = 41, body_pos_id = 8, position_text = "Standing Rear", location_text = "Back of legs (knees down)", dummy_position = 4, X1 = 763323571, Y1 = 1497141596, X2 = 1353627133, Y2 = 2039093305, body_type = 0, bar_location_text = "on WHITE coloured position", light_intensity_text = "Illumination light is on", other_instruction_text = "Choose A, B or C sub-position, depend on patient height.", remark_text = "For this position follow-up, use the same camera bar position and sub position (A, B or C).", hint_text = "16777215" });
            modelBuilder.Entity<DEFBodymapPosition>().HasData(new DEFBodymapPosition { id = 42, body_pos_id = 9, position_text = "Standing Front", location_text = "Upper legs to above knee", dummy_position = 1, X1 = 763323571, Y1 = 1083903418, X2 = 1373982428, Y2 = 1537787974, body_type = 0, bar_location_text = "on YELLOW coloured position", light_intensity_text = "Illumination light is on", other_instruction_text = "Choose A, B or C sub-position, depend on patient height.", remark_text = "For this position follow-up, use the same camera bar position and sub position (A, B or C).", hint_text = "65535" });
            modelBuilder.Entity<DEFBodymapPosition>().HasData(new DEFBodymapPosition { id = 43, body_pos_id = 10, position_text = "Standing Front", location_text = "Both lower legs (knees down)", dummy_position = 1, X1 = 763323571, Y1 = 1537787974, X2 = 1373982428, Y2 = 2039093305, body_type = 0, bar_location_text = "on WHITE coloured position", light_intensity_text = "Illumination light is on", other_instruction_text = "Choose A, B or C sub-position, depend on patient height.", remark_text = "For this position follow-up, use the same camera bar position and sub position (A, B or C).", hint_text = "16777215" });
            modelBuilder.Entity<DEFBodymapPosition>().HasData(new DEFBodymapPosition { id = 44, body_pos_id = 1, position_text = "Sitting in chair", location_text = "Front face and neck", dummy_position = 7, X1 = 10177648, Y1 = 6774396, X2 = 1048297704, Y2 = 1063580229, body_type = 3, bar_location_text = "on BLUE coloured position", light_intensity_text = "Illumination light is on", other_instruction_text = "Choose A, B or C sub-position, depend on patient height.", remark_text = "For this position follow-up, use the same camera bar position and sub position (A, B or C).", hint_text = "14390128" });
            modelBuilder.Entity<DEFBodymapPosition>().HasData(new DEFBodymapPosition { id = 45, body_pos_id = 2, position_text = "Sitting in chair", location_text = "Right face and neck", dummy_position = 7, X1 = 10177648, Y1 = 1090677814, X2 = 1048297704, Y2 = 2147483647, body_type = 3, bar_location_text = "on BLUE coloured position", light_intensity_text = "Illumination light is on", other_instruction_text = "Choose A, B or C sub-position, depend on patient height.", remark_text = "For this position follow-up, use the same camera bar position and sub position (A, B or C).", hint_text = "14390128" });
            modelBuilder.Entity<DEFBodymapPosition>().HasData(new DEFBodymapPosition { id = 46, body_pos_id = 3, position_text = "Sitting in chair", location_text = "Left face and neck", dummy_position = 7, X1 = 1089008295, Y1 = 6774396, X2 = 2137305999, Y2 = 1063580229, body_type = 3, bar_location_text = "on BLUE coloured position", light_intensity_text = "Illumination light is on", other_instruction_text = "Choose A, B or C sub-position, depend on patient height.", remark_text = "For this position follow-up, use the same camera bar position and sub position (A, B or C).", hint_text = "14390128" });
            modelBuilder.Entity<DEFBodymapPosition>().HasData(new DEFBodymapPosition { id = 47, body_pos_id = 4, position_text = "Sitting in chair", location_text = "Sole of right foot", dummy_position = 9, X1 = 10177648, Y1 = 1090677814, X2 = 1048297704, Y2 = 2147483647, body_type = 3, bar_location_text = "on WHITE coloured position", light_intensity_text = "Illumination light is on", other_instruction_text = "Choose A, B or C sub-position, depend on patient height.", remark_text = "For this position follow-up, use the same camera bar position and sub position (A, B or C).", hint_text = "16777215" });
            modelBuilder.Entity<DEFBodymapPosition>().HasData(new DEFBodymapPosition { id = 48, body_pos_id = 5, position_text = "Sitting in chair", location_text = "Sole of left foot", dummy_position = 9, X1 = 1089008295, Y1 = 1090677814, X2 = 2137305999, Y2 = 2147483647, body_type = 3, bar_location_text = "on WHITE coloured position", light_intensity_text = "Illumination light is on", other_instruction_text = "Choose A, B or C sub-position, depend on patient height.", remark_text = "For this position follow-up, use the same camera bar position and sub position (A, B or C).", hint_text = "16777215" });
            modelBuilder.Entity<DEFBodymapPosition>().HasData(new DEFBodymapPosition { id = 49, body_pos_id = 6, position_text = "Standing Right", location_text = "Right upper arm, anterior, forearm and open hand", dummy_position = 5, X1 = 814211809, Y1 = 108390342, X2 = 1424870666, Y2 = 677439636, body_type = 3, bar_location_text = "on BLUE coloured position", light_intensity_text = "Illumination light is on", other_instruction_text = "Choose A, B or C sub-position, depend on patient height.", remark_text = "For this position follow-up, use the same camera bar position and sub position (A, B or C).", hint_text = "14390128" });
            modelBuilder.Entity<DEFBodymapPosition>().HasData(new DEFBodymapPosition { id = 50, body_pos_id = 7, position_text = "Standing Right", location_text = "Right flank with arm raised", dummy_position = 5, X1 = 742968276, Y1 = 630018862, X2 = 1180607123, Y2 = 989061869, body_type = 3, bar_location_text = "on LIGHT BLUE coloured position", light_intensity_text = "Illumination light is on", other_instruction_text = "Choose A, B or C sub-position, depend on patient height.", remark_text = "For this position follow-up, use the same camera bar position and sub position (A, B or C).", hint_text = "15329708" });
            modelBuilder.Entity<DEFBodymapPosition>().HasData(new DEFBodymapPosition { id = 51, body_pos_id = 8, position_text = "Standing Right", location_text = "Right thigh and hip", dummy_position = 5, X1 = 742968276, Y1 = 989061869, X2 = 1160251828, Y2 = 1544562371, body_type = 3, bar_location_text = "on YELLOW coloured position", light_intensity_text = "Illumination light is on", other_instruction_text = "Choose A, B or C sub-position, depend on patient height.", remark_text = "For this position follow-up, use the same camera bar position and sub position (A, B or C).", hint_text = "65535" });
            modelBuilder.Entity<DEFBodymapPosition>().HasData(new DEFBodymapPosition { id = 52, body_pos_id = 9, position_text = "Standing Right", location_text = "Right lateral calf and foot", dummy_position = 5, X1 = 702257686, Y1 = 1544562371, X2 = 1200962419, Y2 = 2039093305, body_type = 3, bar_location_text = "on WHITE coloured position", light_intensity_text = "Illumination light is on", other_instruction_text = "Choose A, B or C sub-position, depend on patient height.", remark_text = "For this position follow-up, use the same camera bar position and sub position (A, B or C).", hint_text = "16777215" });
            modelBuilder.Entity<DEFBodymapPosition>().HasData(new DEFBodymapPosition { id = 53, body_pos_id = 10, position_text = "Standing Right", location_text = "Left inner arm and hand", dummy_position = 6, X1 = 1099185943, Y1 = 101615945, X2 = 1638601266, Y2 = 657116447, body_type = 3, bar_location_text = "on BLUE coloured position", light_intensity_text = "Illumination light is on", other_instruction_text = "Choose A, B or C sub-position, depend on patient height.", remark_text = "For this position follow-up, use the same camera bar position and sub position (A, B or C).", hint_text = "14390128" });
            modelBuilder.Entity<DEFBodymapPosition>().HasData(new DEFBodymapPosition { id = 54, body_pos_id = 11, position_text = "Standing Left", location_text = "Left upper arm, anterior, forearm and open hand", dummy_position = 3, X1 = 712435333, Y1 = 108390342, X2 = 1333271838, Y2 = 677439636, body_type = 3, bar_location_text = "on BLUE coloured position", light_intensity_text = "Illumination light is on", other_instruction_text = "Choose A, B or C sub-position, depend on patient height.", remark_text = "For this position follow-up, use the same camera bar position and sub position (A, B or C).", hint_text = "14390128" });
            modelBuilder.Entity<DEFBodymapPosition>().HasData(new DEFBodymapPosition { id = 55, body_pos_id = 12, position_text = "Standing Left", location_text = "Left flank with arm raised", dummy_position = 3, X1 = 956698876, Y1 = 630018862, X2 = 1394337723, Y2 = 989061869, body_type = 3, bar_location_text = "on LIGHT BLUE coloured position", light_intensity_text = "Illumination light is on", other_instruction_text = "Choose A, B or C sub-position, depend on patient height.", remark_text = "For this position follow-up, use the same camera bar position and sub position (A, B or C).", hint_text = "15329708" });
            modelBuilder.Entity<DEFBodymapPosition>().HasData(new DEFBodymapPosition { id = 56, body_pos_id = 13, position_text = "Standing Left", location_text = "Left thigh and hip", dummy_position = 3, X1 = 977054171, Y1 = 989061869, X2 = 1394337723, Y2 = 1544562371, body_type = 3, bar_location_text = "on YELLOW coloured position", light_intensity_text = "Illumination light is on", other_instruction_text = "Choose A, B or C sub-position, depend on patient height.", remark_text = "For this position follow-up, use the same camera bar position and sub position (A, B or C).", hint_text = "65535" });
            modelBuilder.Entity<DEFBodymapPosition>().HasData(new DEFBodymapPosition { id = 57, body_pos_id = 14, position_text = "Standing Left", location_text = "Left lateral calf and foot", dummy_position = 3, X1 = 936343581, Y1 = 1544562371, X2 = 1435048314, Y2 = 2039093305, body_type = 3, bar_location_text = "on WHITE coloured position", light_intensity_text = "Illumination light is on", other_instruction_text = "Choose A, B or C sub-position, depend on patient height.", remark_text = "For this position follow-up, use the same camera bar position and sub position (A, B or C).", hint_text = "16777215" });
            modelBuilder.Entity<DEFBodymapPosition>().HasData(new DEFBodymapPosition { id = 58, body_pos_id = 15, position_text = "Standing Left", location_text = "Right inner arm and hand", dummy_position = 2, X1 = 498704733, Y1 = 101615945, X2 = 1038120057, Y2 = 657116447, body_type = 3, bar_location_text = "on BLUE coloured position", light_intensity_text = "Illumination light is on", other_instruction_text = "Choose A, B or C sub-position, depend on patient height.", remark_text = "For this position follow-up, use the same camera bar position and sub position (A, B or C).", hint_text = "14390128" });
            modelBuilder.Entity<DEFBodymapPosition>().HasData(new DEFBodymapPosition { id = 59, body_pos_id = 16, position_text = "Standing Front", location_text = "Left and right chest", dummy_position = 1, X1 = 742968276, Y1 = 406463782, X2 = 1384160076, Y2 = 711311618, body_type = 3, bar_location_text = "on LIGHT BLUE coloured position", light_intensity_text = "Illumination light is on", other_instruction_text = "Choose A, B or C sub-position, depend on patient height.", remark_text = "For this position follow-up, use the same camera bar position and sub position (A, B or C).", hint_text = "15329708" });
            modelBuilder.Entity<DEFBodymapPosition>().HasData(new DEFBodymapPosition { id = 60, body_pos_id = 17, position_text = "Standing Front", location_text = "Left and right abdomen", dummy_position = 1, X1 = 804034162, Y1 = 670665240, X2 = 1323094190, Y2 = 1043257040, body_type = 3, bar_location_text = "on LIGHT BLUE coloured position", light_intensity_text = "Illumination light is on", other_instruction_text = "Choose A, B or C sub-position, depend on patient height.", remark_text = "For this position follow-up, use the same camera bar position and sub position (A, B or C).", hint_text = "15329708" });
            modelBuilder.Entity<DEFBodymapPosition>().HasData(new DEFBodymapPosition { id = 61, body_pos_id = 18, position_text = "Standing Front", location_text = "Upper legs, anterior", dummy_position = 1, X1 = 773501219, Y1 = 1009385058, X2 = 1363804781, Y2 = 1537787974, body_type = 3, bar_location_text = "on YELLOW coloured position", light_intensity_text = "Illumination light is on", other_instruction_text = "Choose A, B or C sub-position, depend on patient height.", remark_text = "For this position follow-up, use the same camera bar position and sub position (A, B or C).", hint_text = "65535" });
            modelBuilder.Entity<DEFBodymapPosition>().HasData(new DEFBodymapPosition { id = 62, body_pos_id = 19, position_text = "Standing Front", location_text = "Lower legs, anterior", dummy_position = 1, X1 = 773501219, Y1 = 1537787974, X2 = 1363804781, Y2 = 2045867702, body_type = 3, bar_location_text = "on WHITE coloured position", light_intensity_text = "Illumination light is on", other_instruction_text = "Choose A, B or C sub-position, depend on patient height.", remark_text = "For this position follow-up, use the same camera bar position and sub position (A, B or C).", hint_text = "16777215" });
            modelBuilder.Entity<DEFBodymapPosition>().HasData(new DEFBodymapPosition { id = 63, body_pos_id = 20, position_text = "Standing Front", location_text = "Right inner leg", dummy_position = 2, X1 = 773501219, Y1 = 1158421778, X2 = 1262028304, Y2 = 2045867702, body_type = 3, bar_location_text = "on WHITE coloured position", light_intensity_text = "Illumination light is on", other_instruction_text = "Choose A, B or C sub-position, depend on patient height.", remark_text = "For this position follow-up, use the same camera bar position and sub position (A, B or C).", hint_text = "16777215" });
            modelBuilder.Entity<DEFBodymapPosition>().HasData(new DEFBodymapPosition { id = 64, body_pos_id = 21, position_text = "Standing Front", location_text = "Left inner leg", dummy_position = 6, X1 = 875277695, Y1 = 1158421778, X2 = 1363804781, Y2 = 2045867702, body_type = 3, bar_location_text = "on WHITE coloured position", light_intensity_text = "Illumination light is on", other_instruction_text = "Choose A, B or C sub-position, depend on patient height.", remark_text = "For this position follow-up, use the same camera bar position and sub position (A, B or C).", hint_text = "16777215" });
            modelBuilder.Entity<DEFBodymapPosition>().HasData(new DEFBodymapPosition { id = 65, body_pos_id = 22, position_text = "Standing Front", location_text = "Both palms", dummy_position = 8, X1 = 10177648, Y1 = 1090677814, X2 = 2137305999, Y2 = 2147483647, body_type = 3, bar_location_text = "on LIGHT BLUE coloured position", light_intensity_text = "Illumination light is on", other_instruction_text = "Choose A, B or C sub-position, depend on patient height.", remark_text = "For this position follow-up, use the same camera bar position and sub position (A, B or C).", hint_text = "15329708" });
            modelBuilder.Entity<DEFBodymapPosition>().HasData(new DEFBodymapPosition { id = 66, body_pos_id = 23, position_text = "Standing Rear", location_text = "Back of neck, upper back and arm, posterior", dummy_position = 4, X1 = 590303562, Y1 = 291299044, X2 = 1536824790, Y2 = 711311618, body_type = 3, bar_location_text = "on LIGHT BLUE coloured position", light_intensity_text = "Illumination light is on", other_instruction_text = "Choose A, B or C sub-position, depend on patient height.", remark_text = "For this position follow-up, use the same camera bar position and sub position (A, B or C).", hint_text = "15329708" });
            modelBuilder.Entity<DEFBodymapPosition>().HasData(new DEFBodymapPosition { id = 67, body_pos_id = 24, position_text = "Standing Rear", location_text = "Lower back and arm, posterior", dummy_position = 4, X1 = 559770619, Y1 = 670665240, X2 = 1577535380, Y2 = 894220320, body_type = 3, bar_location_text = "on LIGHT BLUE coloured position", light_intensity_text = "Illumination light is on", other_instruction_text = "Choose A, B or C sub-position, depend on patient height.", remark_text = "For this position follow-up, use the same camera bar position and sub position (A, B or C).", hint_text = "15329708" });
            modelBuilder.Entity<DEFBodymapPosition>().HasData(new DEFBodymapPosition { id = 68, body_pos_id = 25, position_text = "Standing Rear", location_text = "Buttocks and upper legs, posterior", dummy_position = 4, X1 = 559770619, Y1 = 900994716, X2 = 1577535380, Y2 = 1483592803, body_type = 3, bar_location_text = "on YELLOW coloured position", light_intensity_text = "Illumination light is on", other_instruction_text = "Choose A, B or C sub-position, depend on patient height.", remark_text = "For this position follow-up, use the same camera bar position and sub position (A, B or C).", hint_text = "65535" });
            modelBuilder.Entity<DEFBodymapPosition>().HasData(new DEFBodymapPosition { id = 69, body_pos_id = 26, position_text = "Standing Rear", location_text = "Lower legs, posterior", dummy_position = 4, X1 = 773501219, Y1 = 1490367200, X2 = 1363804781, Y2 = 2045867702, body_type = 3, bar_location_text = "on WHITE coloured position", light_intensity_text = "Illumination light is on", other_instruction_text = "Choose A, B or C sub-position, depend on patient height.", remark_text = "For this position follow-up, use the same camera bar position and sub position (A, B or C).", hint_text = "16777215" });
            #endregion
        }
    }
}
