using System;
using System.Collections.Generic;
using System.Text;
using Microsoft.EntityFrameworkCore;

namespace Molemax.Models
{
    public class DEFLocalTxtSeed
    {
        public static void GenerateSeed(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 1, TxtPos = 20000, TxtLokal = "head" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 2, TxtPos = 20001, TxtLokal = "cervical, right" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 3, TxtPos = 20002, TxtLokal = "cervical, left" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 4, TxtPos = 20003, TxtLokal = "thoracic, right" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 5, TxtPos = 20004, TxtLokal = "thoracic, left" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 6, TxtPos = 20005, TxtLokal = "right shoulder" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 7, TxtPos = 20006, TxtLokal = "left shoulder" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 8, TxtPos = 20007, TxtLokal = "right upper arm" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 9, TxtPos = 20008, TxtLokal = "left upper arm" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 10, TxtPos = 20009, TxtLokal = "right lower arm" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 11, TxtPos = 20010, TxtLokal = "left lower arm" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 12, TxtPos = 20011, TxtLokal = "right hand" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 13, TxtPos = 20012, TxtLokal = "left hand" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 14, TxtPos = 20013, TxtLokal = "right epigastric region" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 15, TxtPos = 20014, TxtLokal = "left epigastric region" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 16, TxtPos = 20015, TxtLokal = "right lower abdomen" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 17, TxtPos = 20016, TxtLokal = "left lower abdomen" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 18, TxtPos = 20017, TxtLokal = "right groin" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 19, TxtPos = 20018, TxtLokal = "left groin" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 20, TxtPos = 20019, TxtLokal = "pubic region" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 21, TxtPos = 20020, TxtLokal = "right thigh, anterior" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 22, TxtPos = 20021, TxtLokal = "left thigh, anterior" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 23, TxtPos = 20022, TxtLokal = "right knee" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 24, TxtPos = 20023, TxtLokal = "left knee" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 25, TxtPos = 20024, TxtLokal = "right lower leg, anterior" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 26, TxtPos = 20025, TxtLokal = "left lower leg, anterior" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 27, TxtPos = 20026, TxtLokal = "right foot" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 28, TxtPos = 20027, TxtLokal = "left foot" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 29, TxtPos = 20028, TxtLokal = "genital spot" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 30, TxtPos = 20029, TxtLokal = "supraclavicular, right" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 31, TxtPos = 20030, TxtLokal = "supraclavicular, left" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 32, TxtPos = 20031, TxtLokal = "right hip" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 33, TxtPos = 20032, TxtLokal = "left hip" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 34, TxtPos = 20035, TxtLokal = "right elbow" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 35, TxtPos = 20036, TxtLokal = "left elbow" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 36, TxtPos = 20037, TxtLokal = "scapular region, right" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 37, TxtPos = 20038, TxtLokal = "scapular region, left" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 38, TxtPos = 20039, TxtLokal = "suprascapular region, right" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 39, TxtPos = 20040, TxtLokal = "suprascapular region, left" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 40, TxtPos = 20041, TxtLokal = "paravertebral, thoracic, right" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 41, TxtPos = 20042, TxtLokal = "paravertebral, thoracic, left" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 42, TxtPos = 20043, TxtLokal = "paravertebral, lumbar, right" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 43, TxtPos = 20044, TxtLokal = "paravertebral, lumbar, left" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 44, TxtPos = 20045, TxtLokal = "thorax, dorsolateral, right" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 45, TxtPos = 20046, TxtLokal = "thorax, dorsolateral, left" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 46, TxtPos = 20047, TxtLokal = "right thigh, posterior" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 47, TxtPos = 20048, TxtLokal = "left thigh, posterior" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 48, TxtPos = 20049, TxtLokal = "right lower leg, posterior" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 49, TxtPos = 20050, TxtLokal = "right heel" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 50, TxtPos = 20051, TxtLokal = "left heel" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 51, TxtPos = 20052, TxtLokal = "left lower leg, posterior" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 52, TxtPos = 20053, TxtLokal = "right upper arm, medial" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 53, TxtPos = 20054, TxtLokal = "right lower arm, medial" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 54, TxtPos = 20055, TxtLokal = "left upper arm, anterior" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 55, TxtPos = 20057, TxtLokal = "left lower arm, anterior" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 56, TxtPos = 20058, TxtLokal = "left upper arm, medial" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 57, TxtPos = 20059, TxtLokal = "left lower arm, medial" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 58, TxtPos = 20060, TxtLokal = "left popliteal cavity" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 59, TxtPos = 20061, TxtLokal = "left flank" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 60, TxtPos = 20062, TxtLokal = "buttocks, left" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 61, TxtPos = 20063, TxtLokal = "left ankle" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 62, TxtPos = 20064, TxtLokal = "left thigh, lateral" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 63, TxtPos = 20065, TxtLokal = "left lower leg, lateral" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 64, TxtPos = 20066, TxtLokal = "back" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 65, TxtPos = 20067, TxtLokal = "right upper arm, anterior" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 66, TxtPos = 20069, TxtLokal = "right lower arm, anterior" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 67, TxtPos = 20070, TxtLokal = "right popliteal cavity" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 68, TxtPos = 20071, TxtLokal = "right flank" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 69, TxtPos = 20072, TxtLokal = "buttocks, right" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 70, TxtPos = 20073, TxtLokal = "right ankle" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 71, TxtPos = 20074, TxtLokal = "right thigh, lateral" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 72, TxtPos = 20075, TxtLokal = "right lower leg, lateral" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 73, TxtPos = 20076, TxtLokal = "right thigh, medial" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 74, TxtPos = 20077, TxtLokal = "right lower leg, medial" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 75, TxtPos = 20078, TxtLokal = "left thigh, medial" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 76, TxtPos = 20079, TxtLokal = "left lower leg, medial" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 77, TxtPos = 20080, TxtLokal = "temporal, right" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 78, TxtPos = 20081, TxtLokal = "temporal, left" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 79, TxtPos = 20082, TxtLokal = "neck, right" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 80, TxtPos = 20083, TxtLokal = "neck, left" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 81, TxtPos = 20084, TxtLokal = "retroauricular, right" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 82, TxtPos = 20085, TxtLokal = "retroauricular, left" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 83, TxtPos = 20086, TxtLokal = "occipital" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 84, TxtPos = 20088, TxtLokal = "orbital region, left" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 85, TxtPos = 20089, TxtLokal = "left eyelid, upper" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 86, TxtPos = 20090, TxtLokal = "left eyelid, lower" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 87, TxtPos = 20091, TxtLokal = "left cheek" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 88, TxtPos = 20092, TxtLokal = "left ear" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 89, TxtPos = 20093, TxtLokal = "front" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 90, TxtPos = 20094, TxtLokal = "nose" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 91, TxtPos = 20095, TxtLokal = "upper lip" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 92, TxtPos = 20096, TxtLokal = "lower lip" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 93, TxtPos = 20097, TxtLokal = "oral region" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 94, TxtPos = 20098, TxtLokal = "chin" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 95, TxtPos = 20099, TxtLokal = "scalp" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 96, TxtPos = 20101, TxtLokal = "orbital region, right" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 97, TxtPos = 20102, TxtLokal = "right eyelid, upper" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 98, TxtPos = 20103, TxtLokal = "right eyelid, lower" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 99, TxtPos = 20104, TxtLokal = "right cheek" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 100, TxtPos = 20105, TxtLokal = "right ear" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 101, TxtPos = 20106, TxtLokal = "left palm" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 102, TxtPos = 20107, TxtLokal = "left back of the hand" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 103, TxtPos = 20108, TxtLokal = "left thumb" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 104, TxtPos = 20109, TxtLokal = "left first finger" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 105, TxtPos = 20110, TxtLokal = "left second finger" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 106, TxtPos = 20111, TxtLokal = "left third finger" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 107, TxtPos = 20112, TxtLokal = "left fourth finger" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 108, TxtPos = 20113, TxtLokal = "right palm" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 109, TxtPos = 20114, TxtLokal = "right back of the hand" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 110, TxtPos = 20115, TxtLokal = "right thumb" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 111, TxtPos = 20116, TxtLokal = "right first finger" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 112, TxtPos = 20117, TxtLokal = "right second finger" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 113, TxtPos = 20118, TxtLokal = "right third finger" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 114, TxtPos = 20119, TxtLokal = "right fourth finger" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 115, TxtPos = 20120, TxtLokal = "left sole" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 116, TxtPos = 20121, TxtLokal = "left dorsum" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 117, TxtPos = 20122, TxtLokal = "great toe, left" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 118, TxtPos = 20123, TxtLokal = "second toe, left" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 119, TxtPos = 20124, TxtLokal = "third toe, left" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 120, TxtPos = 20125, TxtLokal = "forth toe, left" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 121, TxtPos = 20126, TxtLokal = "little toe, left" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 122, TxtPos = 20127, TxtLokal = "left dorsum, lateral" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 123, TxtPos = 20128, TxtLokal = "left dorsum, medial" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 124, TxtPos = 20129, TxtLokal = "right sole" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 125, TxtPos = 20130, TxtLokal = "right dorsum" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 126, TxtPos = 20131, TxtLokal = "great toe, right" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 127, TxtPos = 20132, TxtLokal = "second toe, right" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 128, TxtPos = 20133, TxtLokal = "third toe, right" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 129, TxtPos = 20134, TxtLokal = "forth toe, right" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 130, TxtPos = 20135, TxtLokal = "little toe, right" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 131, TxtPos = 20136, TxtLokal = "right dorsum, lateral" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 132, TxtPos = 20137, TxtLokal = "right dorsum, medial" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 133, TxtPos = 30001, TxtLokal = "back of the head and neck" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 134, TxtPos = 30002, TxtLokal = "buttocks, left" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 135, TxtPos = 30003, TxtLokal = "buttocks, right" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 136, TxtPos = 30004, TxtLokal = "face and neck" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 137, TxtPos = 30005, TxtLokal = "front face and neck" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 138, TxtPos = 30006, TxtLokal = "left abdomen" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 139, TxtPos = 30007, TxtLokal = "left dorsum" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 140, TxtPos = 30008, TxtLokal = "left back of the hand" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 141, TxtPos = 30009, TxtLokal = "left calf, lateral" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 142, TxtPos = 30010, TxtLokal = "left chest" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 143, TxtPos = 30011, TxtLokal = "left face and neck" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 144, TxtPos = 30012, TxtLokal = "left flank" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 145, TxtPos = 30013, TxtLokal = "left foot" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 146, TxtPos = 30014, TxtLokal = "left foot, lateral" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 147, TxtPos = 30015, TxtLokal = "left hand" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 148, TxtPos = 30016, TxtLokal = "left lower arm" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 149, TxtPos = 30017, TxtLokal = "left lower arm, anterior" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 150, TxtPos = 30018, TxtLokal = "left lower arm, medial" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 151, TxtPos = 30019, TxtLokal = "left lower back" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 152, TxtPos = 30020, TxtLokal = "left lower leg" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 153, TxtPos = 30021, TxtLokal = "left lower leg, medial" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 154, TxtPos = 30022, TxtLokal = "left palm" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 155, TxtPos = 30023, TxtLokal = "right sole" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 156, TxtPos = 30024, TxtLokal = "left thigh and hip" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 157, TxtPos = 30025, TxtLokal = "left upper arm" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 158, TxtPos = 30026, TxtLokal = "left upper arm, anterior" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 159, TxtPos = 30027, TxtLokal = "left upper arm, medial" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 160, TxtPos = 30028, TxtLokal = "left upper back" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 161, TxtPos = 30029, TxtLokal = "left upper leg" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 162, TxtPos = 30030, TxtLokal = "left upper leg, medial" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 163, TxtPos = 30031, TxtLokal = "right abdomen" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 164, TxtPos = 30032, TxtLokal = "right dorsum" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 165, TxtPos = 30033, TxtLokal = "right back of the hand" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 166, TxtPos = 30034, TxtLokal = "right calf, lateral" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 167, TxtPos = 30035, TxtLokal = "right chest" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 168, TxtPos = 30036, TxtLokal = "right face and neck" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 169, TxtPos = 30037, TxtLokal = "right flank" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 170, TxtPos = 30038, TxtLokal = "right foot" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 171, TxtPos = 30039, TxtLokal = "right foot, lateral" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 172, TxtPos = 30040, TxtLokal = "right hand" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 173, TxtPos = 30041, TxtLokal = "right lower arm" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 174, TxtPos = 30042, TxtLokal = "right lower arm, anterior" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 175, TxtPos = 30043, TxtLokal = "right lower arm, medial" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 176, TxtPos = 30044, TxtLokal = "right lower back" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 177, TxtPos = 30045, TxtLokal = "right lower leg" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 178, TxtPos = 30046, TxtLokal = "right lower leg, medial" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 179, TxtPos = 30047, TxtLokal = "right palm" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 180, TxtPos = 30048, TxtLokal = "left sole" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 181, TxtPos = 30049, TxtLokal = "right thigh and hip" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 182, TxtPos = 30050, TxtLokal = "right upper arm" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 183, TxtPos = 30051, TxtLokal = "right upper arm, anterior" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 184, TxtPos = 30052, TxtLokal = "right upper arm, medial" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 185, TxtPos = 30053, TxtLokal = "right upper back" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 186, TxtPos = 30054, TxtLokal = "right upper leg" });
            modelBuilder.Entity<DEFLocalTxt>().HasData(new DEFLocalTxt { id = 187, TxtPos = 30055, TxtLokal = "right upper leg, medial" });
        }
    }
}
