using System;
using System.Collections.Generic;
using System.Text;
using Microsoft.EntityFrameworkCore;

namespace Molemax.Models
{
    public class DEFMikroLokalSeed
    {
        public static void GenerateSeed(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 1, PosMann = 1, TxtMann = "ventral", TxtLokal = 20000, r = 0, g = 40, b = 0, Hotspot = 1, Jumppos = 7 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 2, PosMann = 1, TxtMann = "ventral", TxtLokal = 20001, r = 0, g = 80, b = 0, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 3, PosMann = 1, TxtMann = "ventral", TxtLokal = 20002, r = 0, g = 120, b = 0, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 4, PosMann = 1, TxtMann = "ventral", TxtLokal = 20003, r = 0, g = 160, b = 0, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 5, PosMann = 1, TxtMann = "ventral", TxtLokal = 20004, r = 0, g = 200, b = 0, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 6, PosMann = 1, TxtMann = "ventral", TxtLokal = 20005, r = 0, g = 240, b = 0, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 7, PosMann = 1, TxtMann = "ventral", TxtLokal = 20006, r = 40, g = 0, b = 0, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 8, PosMann = 1, TxtMann = "ventral", TxtLokal = 20007, r = 40, g = 40, b = 0, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 9, PosMann = 1, TxtMann = "ventral", TxtLokal = 20008, r = 40, g = 80, b = 0, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 10, PosMann = 1, TxtMann = "ventral", TxtLokal = 20009, r = 40, g = 120, b = 0, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 11, PosMann = 1, TxtMann = "ventral", TxtLokal = 20010, r = 40, g = 160, b = 0, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 12, PosMann = 1, TxtMann = "ventral", TxtLokal = 20011, r = 40, g = 200, b = 0, Hotspot = 1, Jumppos = 8 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 13, PosMann = 1, TxtMann = "ventral", TxtLokal = 20012, r = 40, g = 240, b = 0, Hotspot = 1, Jumppos = 8 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 14, PosMann = 1, TxtMann = "ventral", TxtLokal = 20013, r = 80, g = 0, b = 0, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 15, PosMann = 1, TxtMann = "ventral", TxtLokal = 20014, r = 80, g = 40, b = 0, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 16, PosMann = 1, TxtMann = "ventral", TxtLokal = 20015, r = 80, g = 80, b = 0, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 17, PosMann = 1, TxtMann = "ventral", TxtLokal = 20016, r = 80, g = 120, b = 0, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 18, PosMann = 1, TxtMann = "ventral", TxtLokal = 20017, r = 80, g = 160, b = 0, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 19, PosMann = 1, TxtMann = "ventral", TxtLokal = 20018, r = 80, g = 200, b = 0, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 20, PosMann = 1, TxtMann = "ventral", TxtLokal = 20019, r = 80, g = 240, b = 0, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 21, PosMann = 1, TxtMann = "ventral", TxtLokal = 20020, r = 120, g = 0, b = 0, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 22, PosMann = 1, TxtMann = "ventral", TxtLokal = 20021, r = 120, g = 40, b = 0, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 23, PosMann = 1, TxtMann = "ventral", TxtLokal = 20022, r = 120, g = 80, b = 0, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 24, PosMann = 1, TxtMann = "ventral", TxtLokal = 20023, r = 120, g = 120, b = 0, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 25, PosMann = 1, TxtMann = "ventral", TxtLokal = 20024, r = 120, g = 160, b = 0, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 26, PosMann = 1, TxtMann = "ventral", TxtLokal = 20025, r = 120, g = 200, b = 0, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 27, PosMann = 1, TxtMann = "ventral", TxtLokal = 20026, r = 120, g = 240, b = 0, Hotspot = 1, Jumppos = 9 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 28, PosMann = 1, TxtMann = "ventral", TxtLokal = 20027, r = 160, g = 0, b = 0, Hotspot = 1, Jumppos = 9 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 29, PosMann = 1, TxtMann = "ventral", TxtLokal = 20028, r = 0, g = 60, b = 60, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 30, PosMann = 1, TxtMann = "ventral", TxtLokal = 20029, r = 60, g = 60, b = 60, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 31, PosMann = 1, TxtMann = "ventral", TxtLokal = 20030, r = 60, g = 60, b = 0, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 32, PosMann = 1, TxtMann = "ventral", TxtLokal = 20031, r = 0, g = 0, b = 180, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 33, PosMann = 1, TxtMann = "ventral", TxtLokal = 20032, r = 180, g = 0, b = 0, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 34, PosMann = 2, TxtMann = "medial left", TxtLokal = 20000, r = 0, g = 40, b = 0, Hotspot = 1, Jumppos = 7 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 35, PosMann = 2, TxtMann = "medial left", TxtLokal = 20001, r = 0, g = 80, b = 0, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 36, PosMann = 2, TxtMann = "medial left", TxtLokal = 20002, r = 0, g = 120, b = 0, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 37, PosMann = 2, TxtMann = "medial left", TxtLokal = 20003, r = 0, g = 160, b = 0, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 38, PosMann = 2, TxtMann = "medial left", TxtLokal = 20004, r = 0, g = 200, b = 0, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 39, PosMann = 2, TxtMann = "medial left", TxtLokal = 20006, r = 40, g = 0, b = 0, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 40, PosMann = 2, TxtMann = "medial left", TxtLokal = 20011, r = 40, g = 200, b = 0, Hotspot = 1, Jumppos = 8 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 41, PosMann = 2, TxtMann = "medial left", TxtLokal = 20012, r = 40, g = 240, b = 0, Hotspot = 1, Jumppos = 8 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 42, PosMann = 2, TxtMann = "medial left", TxtLokal = 20013, r = 80, g = 0, b = 0, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 43, PosMann = 2, TxtMann = "medial left", TxtLokal = 20014, r = 80, g = 40, b = 0, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 44, PosMann = 2, TxtMann = "medial left", TxtLokal = 20015, r = 80, g = 80, b = 0, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 45, PosMann = 2, TxtMann = "medial left", TxtLokal = 20016, r = 80, g = 120, b = 0, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 46, PosMann = 2, TxtMann = "medial left", TxtLokal = 20017, r = 80, g = 160, b = 0, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 47, PosMann = 2, TxtMann = "medial left", TxtLokal = 20018, r = 80, g = 200, b = 0, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 48, PosMann = 2, TxtMann = "medial left", TxtLokal = 20019, r = 80, g = 240, b = 0, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 49, PosMann = 2, TxtMann = "medial left", TxtLokal = 20022, r = 120, g = 80, b = 0, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 50, PosMann = 2, TxtMann = "medial left", TxtLokal = 20023, r = 120, g = 120, b = 0, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 51, PosMann = 2, TxtMann = "medial left", TxtLokal = 20026, r = 120, g = 240, b = 0, Hotspot = 1, Jumppos = 9 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 52, PosMann = 2, TxtMann = "medial left", TxtLokal = 20027, r = 160, g = 0, b = 0, Hotspot = 1, Jumppos = 9 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 53, PosMann = 2, TxtMann = "medial left", TxtLokal = 20028, r = 0, g = 60, b = 60, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 54, PosMann = 2, TxtMann = "medial left", TxtLokal = 20029, r = 60, g = 60, b = 60, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 55, PosMann = 2, TxtMann = "medial left", TxtLokal = 20030, r = 60, g = 60, b = 0, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 56, PosMann = 2, TxtMann = "medial left", TxtLokal = 20032, r = 180, g = 0, b = 0, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 57, PosMann = 2, TxtMann = "medial left", TxtLokal = 20053, r = 45, g = 125, b = 225, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 58, PosMann = 2, TxtMann = "medial left", TxtLokal = 20054, r = 45, g = 45, b = 225, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 59, PosMann = 2, TxtMann = "medial left", TxtLokal = 20055, r = 40, g = 80, b = 220, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 60, PosMann = 2, TxtMann = "medial left", TxtLokal = 20057, r = 40, g = 160, b = 220, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 61, PosMann = 2, TxtMann = "medial left", TxtLokal = 20061, r = 200, g = 120, b = 0, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 62, PosMann = 2, TxtMann = "medial left", TxtLokal = 20064, r = 240, g = 240, b = 0, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 63, PosMann = 2, TxtMann = "medial left", TxtLokal = 20065, r = 0, g = 0, b = 80, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 64, PosMann = 2, TxtMann = "medial left", TxtLokal = 20070, r = 240, g = 40, b = 0, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 65, PosMann = 2, TxtMann = "medial left", TxtLokal = 20073, r = 0, g = 0, b = 220, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 66, PosMann = 2, TxtMann = "medial left", TxtLokal = 20076, r = 245, g = 205, b = 5, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 67, PosMann = 2, TxtMann = "medial left", TxtLokal = 20077, r = 5, g = 5, b = 45, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 68, PosMann = 3, TxtMann = "lateral left", TxtLokal = 20000, r = 0, g = 40, b = 0, Hotspot = 1, Jumppos = 7 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 69, PosMann = 3, TxtMann = "lateral left", TxtLokal = 20002, r = 0, g = 120, b = 0, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 70, PosMann = 3, TxtMann = "lateral left", TxtLokal = 20004, r = 0, g = 200, b = 0, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 71, PosMann = 3, TxtMann = "lateral left", TxtLokal = 20006, r = 40, g = 0, b = 0, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 72, PosMann = 3, TxtMann = "lateral left", TxtLokal = 20012, r = 40, g = 240, b = 0, Hotspot = 1, Jumppos = 8 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 73, PosMann = 3, TxtMann = "lateral left", TxtLokal = 20014, r = 80, g = 40, b = 0, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 74, PosMann = 3, TxtMann = "lateral left", TxtLokal = 20016, r = 80, g = 120, b = 0, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 75, PosMann = 3, TxtMann = "lateral left", TxtLokal = 20018, r = 80, g = 200, b = 0, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 76, PosMann = 3, TxtMann = "lateral left", TxtLokal = 20019, r = 80, g = 240, b = 0, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 77, PosMann = 3, TxtMann = "lateral left", TxtLokal = 20023, r = 120, g = 120, b = 0, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 78, PosMann = 3, TxtMann = "lateral left", TxtLokal = 20027, r = 160, g = 0, b = 0, Hotspot = 1, Jumppos = 9 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 79, PosMann = 3, TxtMann = "lateral left", TxtLokal = 20032, r = 180, g = 0, b = 0, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 80, PosMann = 3, TxtMann = "lateral left", TxtLokal = 20036, r = 180, g = 0, b = 100, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 81, PosMann = 3, TxtMann = "lateral left", TxtLokal = 20055, r = 40, g = 80, b = 220, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 82, PosMann = 3, TxtMann = "lateral left", TxtLokal = 20057, r = 40, g = 160, b = 220, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 83, PosMann = 3, TxtMann = "lateral left", TxtLokal = 20060, r = 240, g = 80, b = 0, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 84, PosMann = 3, TxtMann = "lateral left", TxtLokal = 20061, r = 200, g = 120, b = 0, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 85, PosMann = 3, TxtMann = "lateral left", TxtLokal = 20062, r = 0, g = 0, b = 20, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 86, PosMann = 3, TxtMann = "lateral left", TxtLokal = 20063, r = 0, g = 220, b = 0, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 87, PosMann = 3, TxtMann = "lateral left", TxtLokal = 20064, r = 240, g = 240, b = 0, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 88, PosMann = 3, TxtMann = "lateral left", TxtLokal = 20065, r = 0, g = 0, b = 80, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 89, PosMann = 3, TxtMann = "lateral left", TxtLokal = 20066, r = 100, g = 0, b = 0, Hotspot = 1, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 90, PosMann = 4, TxtMann = "dorsal", TxtLokal = 20000, r = 0, g = 40, b = 0, Hotspot = 1, Jumppos = 7 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 91, PosMann = 4, TxtMann = "dorsal", TxtLokal = 20005, r = 0, g = 240, b = 0, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 92, PosMann = 4, TxtMann = "dorsal", TxtLokal = 20006, r = 40, g = 0, b = 0, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 93, PosMann = 4, TxtMann = "dorsal", TxtLokal = 20007, r = 40, g = 40, b = 0, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 94, PosMann = 4, TxtMann = "dorsal", TxtLokal = 20008, r = 40, g = 80, b = 0, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 95, PosMann = 4, TxtMann = "dorsal", TxtLokal = 20009, r = 40, g = 120, b = 0, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 96, PosMann = 4, TxtMann = "dorsal", TxtLokal = 20010, r = 40, g = 160, b = 0, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 97, PosMann = 4, TxtMann = "dorsal", TxtLokal = 20011, r = 40, g = 200, b = 0, Hotspot = 1, Jumppos = 8 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 98, PosMann = 4, TxtMann = "dorsal", TxtLokal = 20012, r = 40, g = 240, b = 0, Hotspot = 1, Jumppos = 8 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 99, PosMann = 4, TxtMann = "dorsal", TxtLokal = 20026, r = 120, g = 240, b = 0, Hotspot = 1, Jumppos = 9 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 100, PosMann = 4, TxtMann = "dorsal", TxtLokal = 20027, r = 160, g = 0, b = 0, Hotspot = 1, Jumppos = 9 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 101, PosMann = 4, TxtMann = "dorsal", TxtLokal = 20031, r = 0, g = 0, b = 180, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 102, PosMann = 4, TxtMann = "dorsal", TxtLokal = 20032, r = 180, g = 0, b = 0, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 103, PosMann = 4, TxtMann = "dorsal", TxtLokal = 20035, r = 0, g = 100, b = 0, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 104, PosMann = 4, TxtMann = "dorsal", TxtLokal = 20036, r = 0, g = 0, b = 100, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 105, PosMann = 4, TxtMann = "dorsal", TxtLokal = 20037, r = 160, g = 120, b = 0, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 106, PosMann = 4, TxtMann = "dorsal", TxtLokal = 20038, r = 160, g = 160, b = 0, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 107, PosMann = 4, TxtMann = "dorsal", TxtLokal = 20039, r = 0, g = 40, b = 100, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 108, PosMann = 4, TxtMann = "dorsal", TxtLokal = 20040, r = 40, g = 100, b = 0, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 109, PosMann = 4, TxtMann = "dorsal", TxtLokal = 20041, r = 160, g = 200, b = 0, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 110, PosMann = 4, TxtMann = "dorsal", TxtLokal = 20042, r = 160, g = 240, b = 0, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 111, PosMann = 4, TxtMann = "dorsal", TxtLokal = 20043, r = 200, g = 0, b = 0, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 112, PosMann = 4, TxtMann = "dorsal", TxtLokal = 20044, r = 200, g = 40, b = 0, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 113, PosMann = 4, TxtMann = "dorsal", TxtLokal = 20045, r = 100, g = 180, b = 0, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 114, PosMann = 4, TxtMann = "dorsal", TxtLokal = 20046, r = 0, g = 180, b = 100, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 115, PosMann = 4, TxtMann = "dorsal", TxtLokal = 20047, r = 200, g = 240, b = 0, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 116, PosMann = 4, TxtMann = "dorsal", TxtLokal = 20048, r = 240, g = 0, b = 0, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 117, PosMann = 4, TxtMann = "dorsal", TxtLokal = 20049, r = 240, g = 120, b = 0, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 118, PosMann = 4, TxtMann = "dorsal", TxtLokal = 20050, r = 0, g = 0, b = 250, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 119, PosMann = 4, TxtMann = "dorsal", TxtLokal = 20051, r = 250, g = 250, b = 250, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 120, PosMann = 4, TxtMann = "dorsal", TxtLokal = 20052, r = 240, g = 160, b = 0, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 121, PosMann = 4, TxtMann = "dorsal", TxtLokal = 20060, r = 240, g = 80, b = 0, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 122, PosMann = 4, TxtMann = "dorsal", TxtLokal = 20061, r = 200, g = 120, b = 0, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 123, PosMann = 4, TxtMann = "dorsal", TxtLokal = 20062, r = 0, g = 0, b = 20, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 124, PosMann = 4, TxtMann = "dorsal", TxtLokal = 20070, r = 240, g = 40, b = 0, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 125, PosMann = 4, TxtMann = "dorsal", TxtLokal = 20071, r = 200, g = 80, b = 0, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 126, PosMann = 4, TxtMann = "dorsal", TxtLokal = 20072, r = 20, g = 0, b = 0, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 127, PosMann = 4, TxtMann = "dorsal", TxtLokal = 20082, r = 160, g = 40, b = 0, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 128, PosMann = 4, TxtMann = "dorsal", TxtLokal = 20083, r = 160, g = 80, b = 0, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 129, PosMann = 5, TxtMann = "lateral right", TxtLokal = 20000, r = 0, g = 40, b = 0, Hotspot = 1, Jumppos = 7 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 130, PosMann = 5, TxtMann = "lateral right", TxtLokal = 20001, r = 0, g = 80, b = 0, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 131, PosMann = 5, TxtMann = "lateral right", TxtLokal = 20003, r = 0, g = 160, b = 0, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 132, PosMann = 5, TxtMann = "lateral right", TxtLokal = 20005, r = 0, g = 240, b = 0, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 133, PosMann = 5, TxtMann = "lateral right", TxtLokal = 20011, r = 40, g = 200, b = 0, Hotspot = 1, Jumppos = 8 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 134, PosMann = 5, TxtMann = "lateral right", TxtLokal = 20013, r = 80, g = 0, b = 0, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 135, PosMann = 5, TxtMann = "lateral right", TxtLokal = 20015, r = 80, g = 80, b = 0, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 136, PosMann = 5, TxtMann = "lateral right", TxtLokal = 20017, r = 80, g = 160, b = 0, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 137, PosMann = 5, TxtMann = "lateral right", TxtLokal = 20019, r = 80, g = 240, b = 0, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 138, PosMann = 5, TxtMann = "lateral right", TxtLokal = 20022, r = 120, g = 80, b = 0, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 139, PosMann = 5, TxtMann = "lateral right", TxtLokal = 20026, r = 120, g = 240, b = 0, Hotspot = 1, Jumppos = 9 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 140, PosMann = 5, TxtMann = "lateral right", TxtLokal = 20031, r = 0, g = 0, b = 180, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 141, PosMann = 5, TxtMann = "lateral right", TxtLokal = 20035, r = 180, g = 100, b = 0, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 142, PosMann = 5, TxtMann = "lateral right", TxtLokal = 20066, r = 100, g = 0, b = 0, Hotspot = 1, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 143, PosMann = 5, TxtMann = "lateral right", TxtLokal = 20067, r = 40, g = 120, b = 220, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 144, PosMann = 5, TxtMann = "lateral right", TxtLokal = 20069, r = 40, g = 40, b = 220, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 145, PosMann = 5, TxtMann = "lateral right", TxtLokal = 20070, r = 240, g = 40, b = 0, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 146, PosMann = 5, TxtMann = "lateral right", TxtLokal = 20071, r = 200, g = 80, b = 0, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 147, PosMann = 5, TxtMann = "lateral right", TxtLokal = 20072, r = 20, g = 0, b = 0, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 148, PosMann = 5, TxtMann = "lateral right", TxtLokal = 20073, r = 0, g = 0, b = 220, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 149, PosMann = 5, TxtMann = "lateral right", TxtLokal = 20074, r = 240, g = 200, b = 0, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 150, PosMann = 5, TxtMann = "lateral right", TxtLokal = 20075, r = 0, g = 0, b = 40, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 151, PosMann = 6, TxtMann = "medial right", TxtLokal = 20000, r = 0, g = 40, b = 0, Hotspot = 1, Jumppos = 7 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 152, PosMann = 6, TxtMann = "medial right", TxtLokal = 20001, r = 0, g = 80, b = 0, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 153, PosMann = 6, TxtMann = "medial right", TxtLokal = 20002, r = 0, g = 120, b = 0, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 154, PosMann = 6, TxtMann = "medial right", TxtLokal = 20003, r = 0, g = 160, b = 0, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 155, PosMann = 6, TxtMann = "medial right", TxtLokal = 20004, r = 0, g = 200, b = 0, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 156, PosMann = 6, TxtMann = "medial right", TxtLokal = 20005, r = 0, g = 240, b = 0, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 157, PosMann = 6, TxtMann = "medial right", TxtLokal = 20011, r = 40, g = 200, b = 0, Hotspot = 1, Jumppos = 8 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 158, PosMann = 6, TxtMann = "medial right", TxtLokal = 20012, r = 40, g = 240, b = 0, Hotspot = 1, Jumppos = 8 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 159, PosMann = 6, TxtMann = "medial right", TxtLokal = 20013, r = 80, g = 0, b = 0, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 160, PosMann = 6, TxtMann = "medial right", TxtLokal = 20014, r = 80, g = 40, b = 0, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 161, PosMann = 6, TxtMann = "medial right", TxtLokal = 20015, r = 80, g = 80, b = 0, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 162, PosMann = 6, TxtMann = "medial right", TxtLokal = 20016, r = 80, g = 120, b = 0, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 163, PosMann = 6, TxtMann = "medial right", TxtLokal = 20017, r = 80, g = 160, b = 0, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 164, PosMann = 6, TxtMann = "medial right", TxtLokal = 20018, r = 80, g = 200, b = 0, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 165, PosMann = 6, TxtMann = "medial right", TxtLokal = 20019, r = 80, g = 240, b = 0, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 166, PosMann = 6, TxtMann = "medial right", TxtLokal = 20022, r = 120, g = 80, b = 0, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 167, PosMann = 6, TxtMann = "medial right", TxtLokal = 20023, r = 120, g = 120, b = 0, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 168, PosMann = 6, TxtMann = "medial right", TxtLokal = 20026, r = 120, g = 240, b = 0, Hotspot = 1, Jumppos = 9 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 169, PosMann = 6, TxtMann = "medial right", TxtLokal = 20027, r = 160, g = 0, b = 0, Hotspot = 1, Jumppos = 9 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 170, PosMann = 6, TxtMann = "medial right", TxtLokal = 20028, r = 0, g = 60, b = 60, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 171, PosMann = 6, TxtMann = "medial right", TxtLokal = 20029, r = 60, g = 60, b = 60, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 172, PosMann = 6, TxtMann = "medial right", TxtLokal = 20030, r = 60, g = 60, b = 0, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 173, PosMann = 6, TxtMann = "medial right", TxtLokal = 20031, r = 0, g = 0, b = 180, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 174, PosMann = 6, TxtMann = "medial right", TxtLokal = 20058, r = 45, g = 85, b = 225, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 175, PosMann = 6, TxtMann = "medial right", TxtLokal = 20059, r = 45, g = 165, b = 225, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 176, PosMann = 6, TxtMann = "medial right", TxtLokal = 20060, r = 240, g = 80, b = 0, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 177, PosMann = 6, TxtMann = "medial right", TxtLokal = 20063, r = 0, g = 220, b = 0, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 178, PosMann = 6, TxtMann = "medial right", TxtLokal = 20067, r = 40, g = 120, b = 220, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 179, PosMann = 6, TxtMann = "medial right", TxtLokal = 20069, r = 40, g = 40, b = 220, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 180, PosMann = 6, TxtMann = "medial right", TxtLokal = 20071, r = 200, g = 80, b = 0, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 181, PosMann = 6, TxtMann = "medial right", TxtLokal = 20074, r = 240, g = 200, b = 0, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 182, PosMann = 6, TxtMann = "medial right", TxtLokal = 20075, r = 0, g = 0, b = 40, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 183, PosMann = 6, TxtMann = "medial right", TxtLokal = 20078, r = 245, g = 245, b = 5, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 184, PosMann = 6, TxtMann = "medial right", TxtLokal = 20079, r = 5, g = 5, b = 85, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 185, PosMann = 7, TxtMann = "Head", TxtLokal = 20001, r = 0, g = 80, b = 0, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 186, PosMann = 7, TxtMann = "Head", TxtLokal = 20002, r = 0, g = 120, b = 0, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 187, PosMann = 7, TxtMann = "Head", TxtLokal = 20080, r = 220, g = 0, b = 20, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 188, PosMann = 7, TxtMann = "Head", TxtLokal = 20081, r = 220, g = 20, b = 0, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 189, PosMann = 7, TxtMann = "Head", TxtLokal = 20082, r = 160, g = 40, b = 0, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 190, PosMann = 7, TxtMann = "Head", TxtLokal = 20083, r = 160, g = 80, b = 0, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 191, PosMann = 7, TxtMann = "Head", TxtLokal = 20084, r = 70, g = 0, b = 70, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 192, PosMann = 7, TxtMann = "Head", TxtLokal = 20085, r = 70, g = 0, b = 0, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 193, PosMann = 7, TxtMann = "Head", TxtLokal = 20086, r = 0, g = 70, b = 0, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 194, PosMann = 7, TxtMann = "Head", TxtLokal = 20088, r = 0, g = 0, b = 240, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 195, PosMann = 7, TxtMann = "Head", TxtLokal = 20089, r = 0, g = 40, b = 40, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 196, PosMann = 7, TxtMann = "Head", TxtLokal = 20090, r = 0, g = 40, b = 80, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 197, PosMann = 7, TxtMann = "Head", TxtLokal = 20091, r = 0, g = 40, b = 200, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 198, PosMann = 7, TxtMann = "Head", TxtLokal = 20092, r = 0, g = 80, b = 160, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 199, PosMann = 7, TxtMann = "Head", TxtLokal = 20093, r = 0, g = 40, b = 240, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 200, PosMann = 7, TxtMann = "Head", TxtLokal = 20094, r = 0, g = 40, b = 120, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 201, PosMann = 7, TxtMann = "Head", TxtLokal = 20095, r = 90, g = 90, b = 90, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 202, PosMann = 7, TxtMann = "Head", TxtLokal = 20096, r = 90, g = 0, b = 90, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 203, PosMann = 7, TxtMann = "Head", TxtLokal = 20097, r = 0, g = 80, b = 40, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 204, PosMann = 7, TxtMann = "Head", TxtLokal = 20098, r = 0, g = 80, b = 80, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 205, PosMann = 7, TxtMann = "Head", TxtLokal = 20099, r = 0, g = 0, b = 120, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 206, PosMann = 7, TxtMann = "Head", TxtLokal = 20101, r = 0, g = 0, b = 200, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 207, PosMann = 7, TxtMann = "Head", TxtLokal = 20102, r = 20, g = 40, b = 40, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 208, PosMann = 7, TxtMann = "Head", TxtLokal = 20103, r = 20, g = 40, b = 80, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 209, PosMann = 7, TxtMann = "Head", TxtLokal = 20104, r = 0, g = 40, b = 160, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 210, PosMann = 7, TxtMann = "Head", TxtLokal = 20105, r = 0, g = 80, b = 120, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 211, PosMann = 8, TxtMann = "Hand", TxtLokal = 20106, r = 0, g = 80, b = 240, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 212, PosMann = 8, TxtMann = "Hand", TxtLokal = 20107, r = 0, g = 120, b = 80, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 213, PosMann = 8, TxtMann = "Hand", TxtLokal = 20108, r = 0, g = 120, b = 160, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 214, PosMann = 8, TxtMann = "Hand", TxtLokal = 20109, r = 0, g = 120, b = 240, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 215, PosMann = 8, TxtMann = "Hand", TxtLokal = 20110, r = 0, g = 160, b = 80, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 216, PosMann = 8, TxtMann = "Hand", TxtLokal = 20111, r = 0, g = 160, b = 160, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 217, PosMann = 8, TxtMann = "Hand", TxtLokal = 20112, r = 0, g = 160, b = 240, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 218, PosMann = 8, TxtMann = "Hand", TxtLokal = 20113, r = 0, g = 80, b = 200, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 219, PosMann = 8, TxtMann = "Hand", TxtLokal = 20114, r = 0, g = 120, b = 40, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 220, PosMann = 8, TxtMann = "Hand", TxtLokal = 20115, r = 0, g = 120, b = 120, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 221, PosMann = 8, TxtMann = "Hand", TxtLokal = 20116, r = 0, g = 120, b = 200, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 222, PosMann = 8, TxtMann = "Hand", TxtLokal = 20117, r = 0, g = 160, b = 40, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 223, PosMann = 8, TxtMann = "Hand", TxtLokal = 20118, r = 0, g = 160, b = 120, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 224, PosMann = 8, TxtMann = "Hand", TxtLokal = 20119, r = 0, g = 160, b = 200, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 225, PosMann = 9, TxtMann = "Foot", TxtLokal = 20120, r = 0, g = 200, b = 40, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 226, PosMann = 9, TxtMann = "Foot", TxtLokal = 20121, r = 0, g = 240, b = 80, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 227, PosMann = 9, TxtMann = "Foot", TxtLokal = 20122, r = 0, g = 240, b = 160, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 228, PosMann = 9, TxtMann = "Foot", TxtLokal = 20123, r = 0, g = 240, b = 240, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 229, PosMann = 9, TxtMann = "Foot", TxtLokal = 20124, r = 40, g = 0, b = 80, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 230, PosMann = 9, TxtMann = "Foot", TxtLokal = 20125, r = 40, g = 0, b = 160, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 231, PosMann = 9, TxtMann = "Foot", TxtLokal = 20126, r = 40, g = 0, b = 240, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 232, PosMann = 9, TxtMann = "Foot", TxtLokal = 20127, r = 20, g = 250, b = 0, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 233, PosMann = 9, TxtMann = "Foot", TxtLokal = 20128, r = 0, g = 250, b = 20, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 234, PosMann = 9, TxtMann = "Foot", TxtLokal = 20129, r = 0, g = 200, b = 80, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 235, PosMann = 9, TxtMann = "Foot", TxtLokal = 20130, r = 0, g = 240, b = 40, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 236, PosMann = 9, TxtMann = "Foot", TxtLokal = 20131, r = 0, g = 240, b = 120, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 237, PosMann = 9, TxtMann = "Foot", TxtLokal = 20132, r = 0, g = 240, b = 200, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 238, PosMann = 9, TxtMann = "Foot", TxtLokal = 20133, r = 40, g = 0, b = 40, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 239, PosMann = 9, TxtMann = "Foot", TxtLokal = 20134, r = 40, g = 0, b = 120, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 240, PosMann = 9, TxtMann = "Foot", TxtLokal = 20135, r = 40, g = 0, b = 200, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 241, PosMann = 9, TxtMann = "Foot", TxtLokal = 20136, r = 0, g = 20, b = 250, Hotspot = 0, Jumppos = 0 });
            modelBuilder.Entity<DEFMikroLokal>().HasData(new DEFMikroLokal { id = 242, PosMann = 9, TxtMann = "Foot", TxtLokal = 20137, r = 250, g = 0, b = 20, Hotspot = 0, Jumppos = 0 });
        }
    }
}
